version: '2'

networks:
  net_test:
    external: true

services:
  offchaindb:
    container_name: offchaindb
    image: couchdb:3.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5990:5984"
    networks:
      - net_test

  block-listener:
    container_name: block-listener
    image: block-listener:latest
    restart: always
    build: .
    networks:
      - net_test
    depends_on:
      - offchaindb
