version: '2'

networks:
  net_test:
    external: true

services:
  offchaindb:
    container_name: offchaindb
    image: couchdb:3.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5990:5984"
    networks:
      - net_test

  block-listener:
    container_name: block-listener
    image: chhaileng/block-listener:latest
    restart: always
    volumes:
      - ./wallet:/usr/src/app/wallet
      - ./connection-profile:/usr/src/app/connection-profile
    networks:
      - net_test
    depends_on:
      - offchaindb
